BEGIN;

ALTER TABLE collection_areas
    ADD COLUMN IF NOT EXISTS location VARCHAR(500),
    ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS place_id VARCHAR(255);

COMMIT;
